#pragma once
#include "stdafx.h"
enum Monster_Motoin
{
	MONSTERMOTION_IDLE,
	MONSTERMOTION_MOVE,
	MONSTERMOTION_ATK
};
enum MONSTER_WAY
{
	MONSTERWAY_LEFT,
	MONSTERWAY_RIGHT,
	MONSTERWAY_TOP,
	MONSTERWAY_BOTTOM
};